wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686262736.78293
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.3
      5: 0.15.4
      8:
      - 5
